### ISSUE TITLE
Correct measured file

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-emt21-crate#4]
"Waiting for analysis" is not a proper value for a cell

@melinalou

**Comment by melinalou** [comment]
That means to leave it empty or it is not for me?

**Comment by cpavloud** [comment]
It should be NA probably. This is what Katrina mentioned in her e-mails, that she prefers NAs from having empty cells.

**Comment by melinalou** [comment]
done

**Comment by cpavloud** [comment]
Please confirm that this is also changed in the google spreadsheets.

**Comment by melinalou** [comment]
confirmed
